# Allianz-Marine -ContractPDFContrroller 
public with sharing class ContractPDFController {
  public Contract__c ct { get; set; }
  public List<Contract_Vessels__c> vesselLineItems { get; set; }

  public ContractPDFController(ApexPages.StandardController controller) {
    String recordId = ApexPages.currentPage().getParameters().get('id');
    vesselLineItems = [
      SELECT
        Id,
        Vessel_Name__r.Name,
        IMO_Number__c,
        Flag_State__c,
        Type__c,
        GRT_NRT__c,
        Summer_DWT__c,
        When_where_built__c,
        Classification_Society__c
      FROM Contract_Vessels__c
      WHERE Contract__c = :recordId
      WITH USER_MODE
      ORDER BY Vessel_Name__r.Name
    ];
    ct = [
      SELECT
        Id,
        Place_and_Date__c,
        Owner_Name__r.Name,
        BRSI2_Law_of_registry__c,
        BRSI3_Place_of_registered_office__c,
        Account__r.Name,
        BRSI3_Law_of_registry__c,
        BRSI5_Date_of_Last_Classification_Survey__c,
        BRSI6_Delivery__c,
        BRSI6_Redelivery__c,
        BRSI7_Latent_Defects_Months__c,
        BRSI8_Port_or_place_of_Delivery__c,
        BRSI9_Delivery_Notices__c,
        BRSI10_Time_for_delivery__c,
        Cancelling_date__c,
        brsi12_Port_or_place_of_redelivery__c,
        brsi13_Redelivery_notices__c,
        BRSI14_Trading_limits__c,
        BRSI15_Bunker_fuels__c,
        BRSI16_Charter_period__c,
        Charter_hire__c,
        Charter_Hire_for_Optional_Period__c,
        BRSI18_Ext_Period_Months__c,
        Declarable_Date__c,
        BRSI19_Rate_of_interest_payable__c,
        BRSI20_Owners_bank_details__c,
        BRSI21_State__c,
        BRSI21_Threshold_amount_AMT__c,
        BRSI21_Expected_Vessel_Life_Years__c,
        Mortgage_s__c,
        BRSI23_Insured_Total_Loss_value__c,
        BRSI24_Insuring_party__c,
        BRSI25_PG_amount_entity__c,
        BRSI26_Dispute_Resolution__c,
        BRSI27_Name_of_Builders__c,
        BRSI27_Number__c,
        BRSI27_Date_of_newbuilding_contract__c,
        BRSI27_LD_Defect_Penalty_State_Party__c,
        BR27Delivery_L_Delay_Penalty_State_Party__c,
        Purchase_Option__c,
        BRSI29_Underlying_Registry__c,
        Bareboat_Charter_Registry__c,
        BRSI30_Notices_to_Owners__c,
        BRSI31_Notices_to_Charterers__c,
        Customer_Signed_By__r.Name,
        Company_Signed_By__r.Name,
        S171_Reference_Number__c,
        Owners_Place_of_Business__c,
        Charterers_Place_of_business__c,
        S175Date_of_Delivery__c,
        S178Number_of_days_notice_of__c,
        S179Period_of_hire__c,
        S1710Period_of_extension__c,
        S1710Advance_notice_for_declaration__c,
        S1711Voyage_or_well__c,
        S1711Max_extensio_period_state_no_of_Day__c,
        ST712Lump_sum__c,
        S1712When_due__c,
        S1713If_yes_state_amount_of_hire__c,
        S1714Number_of_days_notice_of_early__c,
        S1715Demobilisation_fee__c,
        S1716Area_of_Operation__c,
        S1717_Employment_of_vessel_restricted_to__c,
        S1718State_if_vessel_may_be_used_for_ROV__c,
        S1718State_if_vessel_may_be_employed__c,
        S1719QTY_of_fuel_on_delivery_and_redeliv__c,
        S1719Payment_method_for_fuel_state_10__c,
        S1719Pre_agreed_price_of_fuel__c,
        S1719Fuel_spf_and_grades_for_fuel__c,
        S1720State_rate_and_currency__c,
        S1720Exchange_Rate__c,
        S1721Extension_hire__c,
        Issue_Timing_Advance_Arrears__c,
        AS1722lternate_Issuer_if_not_Box_2__c,
        S1722Alternate_Addressee_if_not_Box_3__c,
        S1723Payments__c,
        S17_24_Payment_of_hire_bunker_invoices__c,
        S1725Interest_rate_payable__c,
        S1726_Maximum_audit_period__c,
        S1727_Meals_state_rate_agreed__c,
        S1728_Accommodation_state_rate_agreed__c,
        S1729Sublet__c,
        S1730_War_cancellation__c,
        S1731_Taxes_payable_by_Owners__c,
        S1732Single_consecutive__c,
        CS1732ombined__c,
        S1734_Numbers_of_additional_clauses__c,
        S0518State_if_vsel_may_be_use_diving_p__c,
        S0519Price_of_bunkers_on_delivery__c,
        S0519Price_of_bunkers_on_redelivery__c,
        S522State_whether_to_be_issued_in_ad__c,
        S522State_by_whom_to_be_issued__c,
        Issued_to_others_if_not_Box_3_addressee__c,
        S0531General_Average__c,
        S0533Breakdown_State_period__c,
        S242Date_of_commencement_of_Agreement__c,
        S245Place_of_registered_o_ce__c,
        S244_Name__r.Name,
        S245Company_Name__r.Name,
        S245IMO_Uniqe_Company_Identi_cation_No__c,
        S245Principal_place_of_business__c,
        S246Technical_Management__c,
        S247Crew_Management__c,
        S248Commercial_Management__c,
        S249Chartering_Services_period__c,
        S2410Crew_Insurances__c,
        S2410Insurance_for_persons_proceeding_to__c,
        S2411Insurance_arrangements__c,
        S2412Optional_insurances__c,
        S2413Interest__c,
        S2415Predelivery_management_fee__c,
        S2416Daily_rate__c,
        S2416For_attendance_i_excess_of_no_of_da__c,
        S2417Nominated_bank_account__c,
        S2418Lay_up_period_number_of_months__c,
        S2419Minimum_contract_period__c,
        S2420Management_fee_on_termination__c,
        S2421Severance_Costs__c,
        S2422Law_arbitration__c,
        S2423Email_address_on_behalf_of_Owners__c,
        S2424Email_address_on_behalf_of_Managers__c,
        S2425Notice_to_the_Owners__c,
        S2426Notice_to_the_Managers__c,
        S2414SubclauseyesorNo__c,
        S2412Subclause_state_no_of_days_to_apply__c,
        S2414Subclause_State_fee_if_excl_fr_anl__c,
        S2415Annual_management_fee__c,
        Mutually_Agreed__c
        FROM Contract__c
      WHERE Id = :recordId
      WITH USER_MODE
    ];
  }
}
